// seed-extra.js — Adicione este arquivo ao projeto e importe no server.js
// No server.js, adicione no topo: const seedExtra = require('./seed-extra');
// E chame seedExtra(Produto) após a conexão com MongoDB

const PRODUTOS_EXTRAS = [
  {nome:'Acerola kg',emoji:'🔴',categoria:'Frutas'},
  {nome:'Kiwi kg',emoji:'🥝',categoria:'Frutas'},
  {nome:'Pera Williams kg',emoji:'🍐',categoria:'Frutas'},
  {nome:'Melão Amarelo kg',emoji:'🍈',categoria:'Frutas'},
  {nome:'Uva Rubi kg',emoji:'🍇',categoria:'Frutas'},
  {nome:'Chicória maço',emoji:'🌿',categoria:'Verduras'},
  {nome:'Espinafre maço',emoji:'🥬',categoria:'Verduras'},
  {nome:'Repolho Roxo un',emoji:'🥬',categoria:'Verduras'},
  {nome:'Berinjela kg',emoji:'🟣',categoria:'Legumes'},
  {nome:'Pimentão Amarelo kg',emoji:'🫑',categoria:'Legumes'},
  {nome:'Asa de Frango kg',emoji:'🍗',categoria:'Açougue'},
  {nome:'Frango a Passarinho kg',emoji:'🍗',categoria:'Açougue'},
  {nome:'Fígado Bovino kg',emoji:'🥩',categoria:'Açougue'},
  {nome:'Moela de Frango kg',emoji:'🍗',categoria:'Açougue'},
  {nome:'Músculo kg',emoji:'🥩',categoria:'Açougue'},
  {nome:'Lombo Suíno kg',emoji:'🥩',categoria:'Açougue'},
  {nome:'Linguiça de Frango kg',emoji:'🌭',categoria:'Açougue'},
  {nome:'Presunto de Frango Sadia kg',emoji:'🍖',categoria:'Açougue'},
  {nome:'Hambúrguer Perdigão 672g 12un',emoji:'🍔',categoria:'Açougue'},
  {nome:'Leite Integral Tirol 1L',emoji:'🥛',categoria:'Laticínios'},
  {nome:'Leite Condensado Campo Belo 395g',emoji:'🥛',categoria:'Laticínios'},
  {nome:'Leite em Pó Ninho Forti+ 400g',emoji:'🥛',categoria:'Laticínios'},
  {nome:'Iogurte Natural Integral 170g',emoji:'🥛',categoria:'Laticínios'},
  {nome:'Iogurte Grego Danone 90g',emoji:'🥛',categoria:'Laticínios'},
  {nome:'Iogurte Yopro Proteico 160g',emoji:'🥛',categoria:'Laticínios'},
  {nome:'Manteiga com Sal Itambé 200g',emoji:'🧈',categoria:'Laticínios'},
  {nome:'Manteiga Aviação sem Sal 200g',emoji:'🧈',categoria:'Laticínios'},
  {nome:'Manteiga Vigor com Sal 200g',emoji:'🧈',categoria:'Laticínios'},
  {nome:'Margarina Becel 500g',emoji:'🧈',categoria:'Laticínios'},
  {nome:'Requeijão Nestlé 200g',emoji:'🧀',categoria:'Laticínios'},
  {nome:'Creme de Leite Piracanjuba 200g',emoji:'🥛',categoria:'Laticínios'},
  {nome:'Apresentado Perdigão kg',emoji:'🍖',categoria:'Laticínios'},
  {nome:'Arroz Tio João Branco 1kg',emoji:'🍚',categoria:'Mercearia'},
  {nome:'Arroz Prato Fino 1kg',emoji:'🍚',categoria:'Mercearia'},
  {nome:'Arroz Urbano Branco 5kg',emoji:'🍚',categoria:'Mercearia'},
  {nome:'Arroz Integral Tio João 1kg',emoji:'🍚',categoria:'Mercearia'},
  {nome:'Arroz Integral Namorado 1kg',emoji:'🍚',categoria:'Mercearia'},
  {nome:'Arroz Integral Prato Fino 1kg',emoji:'🍚',categoria:'Mercearia'},
  {nome:'Arroz Integral Urbano 1kg',emoji:'🍚',categoria:'Mercearia'},
  {nome:'Arroz Parboilizado Tio João 5kg',emoji:'🍚',categoria:'Mercearia'},
  {nome:'Feijão Carioca Fazendeiro 1kg',emoji:'🫘',categoria:'Mercearia'},
  {nome:'Feijão Carioca Mistura 500g',emoji:'🫘',categoria:'Mercearia'},
  {nome:'Açúcar Demerara 1kg',emoji:'🍬',categoria:'Mercearia'},
  {nome:'Farinha de Trigo Sol 1kg',emoji:'🌾',categoria:'Mercearia'},
  {nome:'Farinha de Rosca 500g',emoji:'🌾',categoria:'Mercearia'},
  {nome:'Fubá Yoki 1kg',emoji:'🌽',categoria:'Mercearia'},
  {nome:'Macarrão Espaguete Adria 500g',emoji:'🍝',categoria:'Mercearia'},
  {nome:'Macarrão Fusilli Barilla 500g',emoji:'🍝',categoria:'Mercearia'},
  {nome:'Macarrão Penne Barilla 500g',emoji:'🍝',categoria:'Mercearia'},
  {nome:'Azeite Andorinha 500ml',emoji:'🫒',categoria:'Mercearia'},
  {nome:'Óleo de Girassol Liza 900ml',emoji:'🫙',categoria:'Mercearia'},
  {nome:'Óleo de Soja Cocamar 900ml',emoji:'🫙',categoria:'Mercearia'},
  {nome:'Catchup Heinz 397g',emoji:'🍅',categoria:'Mercearia'},
  {nome:'Granola Jasmine 500g',emoji:'🌾',categoria:'Mercearia'},
  {nome:'Canjica Amarela 500g',emoji:'🌽',categoria:'Mercearia'},
  {nome:'Gelatina Royal 250g',emoji:'🟥',categoria:'Mercearia'},
  {nome:'Cereal Sucrilhos Kelloggs 300g',emoji:'🌽',categoria:'Mercearia'},
  {nome:'Biscoito Cream Cracker Adria 200g',emoji:'🫙',categoria:'Mercearia'},
  {nome:'Biscoito Maisena Nestlé 200g',emoji:'🍪',categoria:'Mercearia'},
  {nome:'Biscoito Recheado Negresco 120g',emoji:'🍪',categoria:'Mercearia'},
  {nome:'Biscoito Recheado Trakinas 132g',emoji:'🍪',categoria:'Mercearia'},
  {nome:'Bolacha Maizena Isabela 200g',emoji:'🍪',categoria:'Mercearia'},
  {nome:'Achocolatado Nescau 2kg',emoji:'🍫',categoria:'Mercearia'},
  {nome:'Guaraná Jesus 2L',emoji:'🥤',categoria:'Bebidas'},
  {nome:'Kuat 2L',emoji:'🥤',categoria:'Bebidas'},
  {nome:'Suco Ades Laranja 1L',emoji:'🧃',categoria:'Bebidas'},
  {nome:'Limonada Pronta 500ml',emoji:'🍋',categoria:'Bebidas'},
  {nome:'Água com Gás Lindoya 1L',emoji:'💧',categoria:'Bebidas'},
  {nome:'Água de Coco 1L',emoji:'🥥',categoria:'Bebidas'},
  {nome:'Vinho Tinto Seco 750ml',emoji:'🍷',categoria:'Bebidas'},
  {nome:'Marshmallow Fini 250g',emoji:'🤍',categoria:'Doces'},
  {nome:'Bala Fini 100g',emoji:'🍬',categoria:'Doces'},
  {nome:'Chiclete Trident 8un',emoji:'🟢',categoria:'Doces'},
  {nome:'Pirulito Chupa Chups un',emoji:'🍭',categoria:'Doces'},
  {nome:'Pé de Moleque Barra 100g',emoji:'🟤',categoria:'Doces'},
  {nome:'Cocada Branca 200g',emoji:'⚪',categoria:'Doces'},
  {nome:'Chocolate Garoto ao Leite 80g',emoji:'🍫',categoria:'Doces'},
  {nome:'Pão Integral Seven Boys 500g',emoji:'🍞',categoria:'Padaria'},
  {nome:'Sonho recheado un',emoji:'🥐',categoria:'Padaria'},
  {nome:'Salgado Frito un',emoji:'🥟',categoria:'Padaria'},
  {nome:'Salgado Assado un',emoji:'🥐',categoria:'Padaria'},
  {nome:'Pizza Seara Calabresa 460g',emoji:'🍕',categoria:'Congelados'},
  {nome:'Lasanha Frango Sadia 600g',emoji:'🫕',categoria:'Congelados'},
  {nome:'Nuggets de Frango Seara 300g',emoji:'🍗',categoria:'Congelados'},
  {nome:'Sorvete Kibon Pote Morango 1,5L',emoji:'🍦',categoria:'Congelados'},
  {nome:'Sorvete Nestlé Pote Napolitano 1,5L',emoji:'🍦',categoria:'Congelados'},
  {nome:'Picolé Kibon Chocolate un',emoji:'🍦',categoria:'Congelados'},
  {nome:'Picolé Kibon Limão un',emoji:'🍦',categoria:'Congelados'},
  {nome:'Picolé Magnum un',emoji:'🍦',categoria:'Congelados'},
  {nome:'Polpa Maracujá 1kg',emoji:'🟣',categoria:'Congelados'},
  {nome:'Polpa Morango 1kg',emoji:'🍓',categoria:'Congelados'},
  {nome:'Açaí Polpa Sambazon 400g',emoji:'💜',categoria:'Congelados'},
  {nome:'Sabão em Pó Brilhante 1kg',emoji:'🧺',categoria:'Limpeza'},
  {nome:'Sabão de Coco em Pedra 200g',emoji:'🧼',categoria:'Limpeza'},
  {nome:'Lava Roupas Omo Líquido 2L',emoji:'🫧',categoria:'Limpeza'},
  {nome:'Tira Manchas Vanish 450g',emoji:'🧴',categoria:'Limpeza'},
  {nome:'Amaciante Fofo 2L',emoji:'🌸',categoria:'Limpeza'},
  {nome:'Detergente Minuano 500ml',emoji:'🫧',categoria:'Limpeza'},
  {nome:'Brilhante Desincrustante 500ml',emoji:'✨',categoria:'Limpeza'},
  {nome:'Desinfetante Flora 1L',emoji:'🧴',categoria:'Limpeza'},
  {nome:'Limpa Vidros Windex 500ml',emoji:'🔵',categoria:'Limpeza'},
  {nome:'Inseticida Raid Aerosol 300ml',emoji:'🟢',categoria:'Limpeza'},
  {nome:'Repelente Off 200ml',emoji:'🟢',categoria:'Limpeza'},
  {nome:'Desentupidor Liquido Destampou 500ml',emoji:'🪣',categoria:'Limpeza'},
  {nome:'Palha de Aço Bombril 8 un',emoji:'🟡',categoria:'Limpeza'},
  {nome:'Rodo 60cm un',emoji:'🧹',categoria:'Limpeza'},
  {nome:'Vassoura Dupla Ação un',emoji:'🧹',categoria:'Limpeza'},
  {nome:'Pano de Prato Kala 3un',emoji:'🤍',categoria:'Limpeza'},
  {nome:'Água Sanitária Ype 1L',emoji:'🧴',categoria:'Limpeza'},
  {nome:'Álcool Líquido Ingleza 70% 1L',emoji:'🧴',categoria:'Limpeza'},
  {nome:'Shampoo Head Shoulders 200ml',emoji:'🧴',categoria:'Higiene'},
  {nome:'Shampoo Seda Ceramidas 325ml',emoji:'🧴',categoria:'Higiene'},
  {nome:'Condicionador Pantene 400ml',emoji:'🧴',categoria:'Higiene'},
  {nome:'Máscara Capilar Elseve 300ml',emoji:'🧴',categoria:'Higiene'},
  {nome:'Creme para Cabelo Salon Line 300g',emoji:'🧴',categoria:'Higiene'},
  {nome:'Creme para Pentear Novex 300g',emoji:'🧴',categoria:'Higiene'},
  {nome:'Gel Capilar Fixador Taft 250ml',emoji:'🧴',categoria:'Higiene'},
  {nome:'Óleo Capilar Wella 30ml',emoji:'🧴',categoria:'Higiene'},
  {nome:'Escova Dental Colgate 1un',emoji:'🦷',categoria:'Higiene'},
  {nome:'Desodorante Nívea Roll-On 50ml',emoji:'🌸',categoria:'Higiene'},
  {nome:'Creme Facial Nivea Antissinais 50ml',emoji:'🧴',categoria:'Higiene'},
  {nome:'Hidratante Corporal Dove 400ml',emoji:'🧴',categoria:'Higiene'},
  {nome:'Hidratante Corporal Nivea 400ml',emoji:'🧴',categoria:'Higiene'},
  {nome:'Cera Squeeze Johnson 200ml',emoji:'🧴',categoria:'Higiene'},
  {nome:'Algodão Johnson 50g',emoji:'⚪',categoria:'Higiene'},
  {nome:'Cotonete Johnson 75un',emoji:'⚪',categoria:'Higiene'},
  {nome:'Lâmina Gillette Prestobarba 2un',emoji:'🪒',categoria:'Higiene'},
  {nome:'Protetor Solar Neutrogena FPS70 200ml',emoji:'🌞',categoria:'Higiene'},
  {nome:'Protetor Solar Sundown FPS50 200ml',emoji:'🌞',categoria:'Higiene'},
  {nome:'Protetor Solar Episol FPS50 120ml',emoji:'🌞',categoria:'Higiene'},
  {nome:'Demaquilante Bifásico Océane 120ml',emoji:'🧴',categoria:'Higiene'},
  {nome:'Demaquilante Nivea 200ml',emoji:'🧴',categoria:'Higiene'},
  {nome:'Base Maybelline Fit Me 30ml',emoji:'💄',categoria:'Cosméticos'},
  {nome:'Batom Avon un',emoji:'💄',categoria:'Cosméticos'},
  {nome:'Batom Maybelline un',emoji:'💄',categoria:'Cosméticos'},
  {nome:'Batom Natura un',emoji:'💄',categoria:'Cosméticos'},
  {nome:'Blush Avon un',emoji:'🌸',categoria:'Cosméticos'},
  {nome:'Colônia Avon un',emoji:'💐',categoria:'Cosméticos'},
  {nome:'Corretivo Maybelline Instant Age un',emoji:'💄',categoria:'Cosméticos'},
  {nome:'Delineador Dailus un',emoji:'✏️',categoria:'Cosméticos'},
  {nome:'Esmalte Risqué un',emoji:'💅',categoria:'Cosméticos'},
  {nome:'Esmalte Colorama un',emoji:'💅',categoria:'Cosméticos'},
  {nome:'Esmalte OPI un',emoji:'💅',categoria:'Cosméticos'},
  {nome:'Espelho de Bolso un',emoji:'🪞',categoria:'Cosméticos'},
  {nome:'Iluminador Dailus un',emoji:'✨',categoria:'Cosméticos'},
  {nome:'Paleta de Sombras Ruby Rose un',emoji:'🎨',categoria:'Cosméticos'},
  {nome:'Perfume Feminino Natura una 75ml',emoji:'💐',categoria:'Cosméticos'},
  {nome:'Perfume Masculino Natura Humor 75ml',emoji:'💐',categoria:'Cosméticos'},
  {nome:'Pinça de Sobrancelha un',emoji:'🔧',categoria:'Cosméticos'},
  {nome:'Pó Compacto Avon un',emoji:'💄',categoria:'Cosméticos'},
  {nome:'Pó Compacto Maybelline un',emoji:'💄',categoria:'Cosméticos'},
  {nome:'Rímel Avon Super Extend un',emoji:'👁️',categoria:'Cosméticos'},
  {nome:'Rímel Maybelline Lash Sensational un',emoji:'👁️',categoria:'Cosméticos'},
  {nome:'Sombra Jasmyne un',emoji:'🎨',categoria:'Cosméticos'},
  {nome:'Tintura de Cabelo Garnier un',emoji:'💇',categoria:'Cosméticos'},
  {nome:'Tintura de Cabelo Igora un',emoji:'💇',categoria:'Cosméticos'},
  {nome:'Acetona Kolene 100ml',emoji:'💅',categoria:'Utilidades'},
  {nome:'Pilha AA Philips 4un',emoji:'🔋',categoria:'Utilidades'},
  {nome:'Prato Descartável 15cm 10un',emoji:'🍽️',categoria:'Utilidades'},
  {nome:'Papel Manteiga 25cm',emoji:'🟡',categoria:'Utilidades'},
  {nome:'Sal Marinho Integral 500g',emoji:'🧂',categoria:'Utilidades'},
];

module.exports = async function seedExtra(Produto) {
  try {
    const existentes = await Produto.find({}, 'nome ativo');
    const nomesTodos = new Set(existentes.map(p => p.nome.toLowerCase().replace(/\s+/g,' ').trim()));
    const novos = PRODUTOS_EXTRAS.filter(p => !nomesTodos.has(p.nome.toLowerCase().replace(/\s+/g,' ').trim()));
    if (novos.length) {
      await Produto.insertMany(novos, { ordered: false }).catch(()=>{});
      console.log(`✅ seed-extra: +${novos.length} produtos adicionados`);
    }
    // Reativar inativados
    const inativos = existentes.filter(p => {
      const n = p.nome.toLowerCase().replace(/\s+/g,' ').trim();
      return PRODUTOS_EXTRAS.some(s => s.nome.toLowerCase().replace(/\s+/g,' ').trim() === n) && !p.ativo;
    });
    if (inativos.length) {
      await Produto.updateMany({ _id: { $in: inativos.map(p => p._id) } }, { ativo: true });
      console.log(`✅ seed-extra: ${inativos.length} produtos reativados`);
    }
    if (!novos.length && !inativos.length) {
      console.log('✅ seed-extra: já completo');
    }
  } catch(e) { console.error('seed-extra erro:', e.message); }
};
